[package]
name = "git-metrics"
description = "A git extension to store metrics directly in git, using the notes."
authors = ["Jeremie Drouet <jeremie.drouet@gmail.com>"]
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive", "env"] }
git2 = { version = "0.18.3" }
indexmap = { version = "2.2.6", features = ["serde"] }
serde = { version = "1.0.200", features = ["derive"] }
thiserror = { version = "1.0.60" }
toml = { version = "0.8.12", features = ["preserve_order"] }
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18" }

[dev-dependencies]
mockall = "0.12.1"
