[package]
name = "git-metrics"
description = "A git extension to store metrics directly in git, using the notes."
authors = ["Jeremie Drouet <jeremie.drouet@gmail.com>"]
license = "MIT"
version = "0.1.3"
edition = "2021"

[features]
default = ["impl-command", "impl-git2"]
impl-command = []
impl-git2 = ["dep:git2", "dep:auth-git2"]

[dependencies]
auth-git2 = { version = "0.5.4", optional = true, features = ["log"] }
clap = { version = "4.5.4", features = ["derive", "env"] }
git2 = { version = "0.18.3", optional = true }
indexmap = { version = "2.2.6", features = ["serde"] }
serde = { version = "1.0.200", features = ["derive"] }
thiserror = { version = "1.0.60" }
toml = { version = "0.8.12", features = ["preserve_order"] }
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18" }

[dev-dependencies]
mockall = "0.12.1"
tempfile = "3.10.1"
test-case = "3.3.1"

[workspace.metadata.cross.target.aarch64-unknown-linux-gnu]
# Install git:arm64, see <https://github.com/cross-rs/cross/blob/main/docs/custom_images.md#adding-dependencies-to-existing-images>
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install git:$CROSS_DEB_ARCH",
]

[workspace.metadata.cross.target.x86_64-unknown-linux-gnu]
# Install git:arm64, see <https://github.com/cross-rs/cross/blob/main/docs/custom_images.md#adding-dependencies-to-existing-images>
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install git:$CROSS_DEB_ARCH",
]
