name: dogfooding

on:
  merge_group:
    types: [checks_requested]
  workflow_call:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  monitor-binary-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: build the binary
        run: cargo build --release

      - name: write binary size metric
        run: |
          git config --global user.name 'Git Metrics Bot'
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          BINARY_SIZE=$(ls -la target/release/git-metrics | cut -d ' ' -f 5)
          RUSTC_VERSION=$(rustc --version)
          target/release/git-metrics add binary-size --tag "platform.arch: $RUNNER_ARCH" --tag "platform.os: $RUNNER_OS" --tag "rust.version: $RUSTC_VERSION" $BINARY_SIZE
          git push origin refs/notes/metrics
