name: integration testing

on:
  # note that HEAD for pull requests represents the merge commit
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  push-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: build binary
        run: cargo build --release

      - name: set git user
        uses: ./.github/actions/git-user

      - name: fetch remote metrics
        run: git fetch origin refs/notes/metrics:refs/notes/metrics

      - name: create metrics
        run: |
          ./target/release/git-metrics add \
            binary-size \
            --tag "unit: byte" \
            --tag "platform.arch: $RUNNER_ARCH" \
            --tag "platform.os: $RUNNER_OS" \
            --tag "rust.version: $(rustc --version)" \
            $(stat --printf="%s" target/release/git-metrics)

      - name: check metrics exist
        run: |
          if [ -z "$(./target/release/git-metrics show)" ]; then
            echo "NO METRICS FOUND"
            exit 1;
          fi

      - name: push metrics
        run: git push origin refs/notes/metrics

      - name: save compiled binary
        uses: actions/upload-artifact@master
        with:
          name: git-metrics-binary
          path: target/release/git-metrics

  check-metrics:
    runs-on: ubuntu-latest
    needs:
      - push-metrics
    steps:
      - uses: actions/checkout@v3
      - name: fetch compiled binary
        uses: actions/download-artifact@master
        with:
          name: git-metrics-binary
          path: target/release

      - name: set git user
        uses: ./.github/actions/git-user

      - name: fetch remote metrics
        run: git fetch origin refs/notes/metrics:refs/notes/metrics

      - name: make git-metrics executable
        run: chmod +x target/release/git-metrics

      - name: check metrics exist
        run: |
          if [ -z "$(./target/release/git-metrics show)" ]; then
            echo "NO METRICS FOUND"
            exit 1;
          fi
