name: integration testing

on:
  # note that HEAD for pull requests represents the merge commit
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  with-git2-push-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: set git user
        uses: ./.github/actions/git-user

      - name: fetch remote metrics
        run: cargo run -- --backend git2 pull

      - name: add metric
        run: cargo run -- --backend git2 add with-git2 1.0

      - name: push metrics
        run: cargo run -- --backend git2 -vvvvv push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  with-git2-pull-metrics:
    runs-on: ubuntu-latest
    needs:
      - with-git2-push-metrics
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: set git user
        uses: ./.github/actions/git-user

      - name: fetch remote metrics
        run: cargo run -- --backend git2 pull

      - name: check metric presence
        run: if [ ! -z "$(cargo run -- --backend git2 show)" ]; then exit 1; fi
