name: release

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_tag:
        description: "version of the release"
        required: true
        type: string

jobs:
  build-macos-binaries:
    name: build macos binaries
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: build binary
        run: |
          cargo build --release
          strip target/release/git-metrics
      - name: set git user
        uses: ./.github/actions/git-user

      - name: add metrics
        run: |
          ./target/release/git-metrics --backend command pull
          binary_size=$(stat -f '%z' ./target/release/git-metrics)
          ./target/release/git-metrics add binary-size \
              --tag "build.target: x86_64-apple-darwin" \
              --tag "platform.os: macos" \
              --tag "platform.arch: x86_64" \
              --tag "unit: byte" \
              $binary_size
          ./target/release/git-metrics --backend command push

      - run: mv ./target/release/git-metrics ./git-metrics_darwin-x86_64
      - uses: actions/upload-artifact@v4
        with:
          name: binary-darwin
          path: git-metrics_darwin-*
          if-no-files-found: error

  build-linux-binaries:
    name: build linux binaries
    runs-on: ubuntu-latest
    needs:
      - build-macos-binaries
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up qemu
        uses: docker/setup-qemu-action@v3
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: build binaries using buildx
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=local,dest=${{ github.workspace }}
          platforms: linux/amd64,linux/arm64
          push: false
          target: binary
      - name: move binaries
        run: |
          mv ./linux_amd64/git-metrics ./git-metrics_linux-x86_64
          mv ./linux_arm64/git-metrics ./git-metrics_linux-aarch64

      - name: set git user
        uses: ./.github/actions/git-user

      - name: make binary executable
        run: chmod +x ./git-metrics_linux-x86_64

      - name: add metrics
        run: |
          ./git-metrics_linux-x86_64 --backend command pull
          ./git-metrics_linux-x86_64 add binary-size \
              --tag "build.target: x86_64-unknown-linux-gnu" \
              --tag "platform.os: linux" \
              --tag "platform.arch: x86_64" \
              --tag "unit: byte" \
              $(stat --printf="%s" ./git-metrics_linux-x86_64)
          ./git-metrics_linux-x86_64 add binary-size \
              --tag "build.target: aarch64-unknown-linux-gnu" \
              --tag "platform.os: linux" \
              --tag "platform.arch: aarch64" \
              --tag "unit: byte" \
              $(stat --printf="%s" ./git-metrics_linux-aarch64)
          ./git-metrics_linux-x86_64 --backend command push

      - uses: actions/upload-artifact@v4
        with:
          name: binary-linux
          path: ./git-metrics_linux-*
          if-no-files-found: error

  publish:
    name: publish
    runs-on: ubuntu-latest
    needs:
      - build-macos-binaries
      - build-linux-binaries
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binary-darwin
      - uses: actions/download-artifact@v4
        with:
          name: binary-linux
      - run: ls -lha *
      - name: get release id from tag
        id: release_id
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch' }}
        run: |
          release_id=$(curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/releases/tags/${{ inputs.release_tag }} | jq .id)
          echo "release_id=$release_id" >> $GITHUB_OUTPUT
      - name: upload the artifacts
        uses: skx/github-action-publish-binaries@release-2.0
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ steps.release_id.outputs.release_id }}
          args: "git-metrics_*"
