name: git-metrics release

on:
  pull_request:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "version of the release"
        required: true
        type: string

jobs:
  build-linux-binaries:
    name: build linux binary for ${{ matrix.platform.release_for }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      matrix:
        platform:
          - release_for: linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            filename: git-metrics_linux-x86_64
            command: build

          - release_for: linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            filename: git-metrics_linux-aarch64
            command: build

          - release_for: macos-x86_64
            os: macos-latest
            target: x86_64-apple-darwin
            filename: git-metrics_macos-x86_64
            command: build

          - release_for: macos-aarch64
            os: macos-latest
            target: aarch64-apple-darwin
            filename: git-metrics_macos-aarch64
            command: build

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release --no-default-features --features impl-command"
          strip: true
      - name: move binary file
        if: ${{ github.ref == 'refs/heads/main' }}
        run: mv target/${{ matrix.platform.target }}/release/git-metrics target/${{ matrix.platform.filename }}
      - uses: actions/upload-artifact@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          name: ${{ matrix.platform.release_for }}
          path: target/${{ matrix.platform.filename }}

  release-binaries:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - build-linux-binaries
    steps:
      - name: download linux x86_64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-x86_64
      - name: download linux aarch64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-aarch64
      - name: download macos x86_64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-x86_64
      - name: download macos aarch64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-aarch64

      - name: display downloaded files
        run: ls -R
      - name: get release id from tag
        id: release_id
        run: |
          release_id=$(curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/releases/tags/${{ inputs.release_tag }} | jq .id)
          echo $release_id
          echo "release_id=$release_id" >> $GITHUB_OUTPUT
      - name: upload the artifacts
        uses: skx/github-action-publish-binaries@release-2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ steps.release_id.outputs.release_id }}
          args: "git-metrics_*"
