name: release

on:
  pull_request:
    paths:
      - ".github/workflows/release.yml"
      - "rust-toolchain.toml"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**.rs"

  push:
    branches:
      - main
    paths:
      - ".github/workflows/release.yml"
      - "rust-toolchain.toml"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**.rs"

jobs:
  build-linux-x86_64:
    name: build linux x86_64 binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: x86_64-unknown-linux-gnu
      - name: build binary
        run: cargo build --release --target x86_64-unknown-linux-gnu
      - name: strip binary
        run: strip target/x86_64-unknown-linux-gnu/release/git-metrics
      - name: rename binary
        run: mv target/x86_64-unknown-linux-gnu/release/git-metrics ./git-metrics_linux-x86_64

  build-linux-aarch64:
    name: build linux aarch64 binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: aarch64-unknown-linux-gnu
      - run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get --assume-yes install libssl-dev:arm64
      - name: build binary
        run: cargo build --release --target aarch64-unknown-linux-gnu
      - name: strip binary
        run: strip target/aarch64-unknown-linux-gnu/release/git-metrics
      - name: rename binary
        run: mv target/aarch64-unknown-linux-gnu/release/git-metrics ./git-metrics_linux-aarch64
